# Travis CI script

language:
- c

cache:
- ccache

osx_image: xcode11

dist: 
- focal

env:
  global:
    - SPHACTOR_SOCKET_LIMIT=20

addons:
  apt:
    packages: &base_deps
    - git
    - mesa-common-dev
    - libasound2-dev
    - libglew-dev
    - libunwind-dev
#  homebrew: &base_deps
#    packages:
#    - binutils
#    - valgrind

matrix:
  include:
  - env: BUILD_TYPE=default
    os: osx
    addons:
  - env: BUILD_TYPE=default
    os: linux

before_install:
- if [ -n "${MATRIX_EVAL}" ] ; then eval ${MATRIX_EVAL} ; fi

install:
  - git submodule update --init --recursive

  # libzmq
  - git clone --depth=1 --branch=master https://github.com/zeromq/libzmq
  - cd libzmq
  - ./autogen.sh
  - ./configure
  - sudo make install
  - cd -

  # python
  - export BUILD_DIR=$TRAVIS_BUILD_DIR/build
  - mkdir $BUILD_DIR
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then 
        ./dist/osx/build_python.sh $BUILD_DIR/python ; 
    fi


script:
  ############################################################################
  # Build main and tests
  ############################################################################
    - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_PULL_REQUEST" == "false" ]; 
        then export CMAKE_OPTIONS="-DPython3_ROOT_DIR=$BUILD_DIR/python -DWITH_EMBED_PYTHON=ON";
      fi
    - mkdir -p build
    - cd build
    - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage .. 
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make install; else make; fi

  # test
# Skip for now!
#    - mv ../test.txt ./bin/test.txt
#    - cd bin
#    - if [ "$BUILD_TYPE" == "valgrind" ] ; then valgrind --leak-check=yes ./gazebosc -test ; fi
#    - if [ "$BUILD_TYPE" != "valgrind" ] ; then ./gazebosc -test ; fi

git:
  depth: 100

after_success:
    #- cd build
    # fixes the osx bundle
    #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then make install ; fi

deploy:
  # TODO
